# Generated by Django 4.1.2 on 2022-10-31 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='verification_code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 17, 0, 18, 9242)),
        ),
    ]
